version: '3.9'

services:

  django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.27
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      - MYSQL_USER=santi2686
      - MYSQL_PASSWORD=S@nti2686
      - MYSQL_DATABASE=plagiarism_detector